### ISSUE TITLE
Is this work on live AWS server ( Linux )

### ISSUE THREAD

**Issue by pavithra-01** [legraphista/node-server-screenshot#13]
Hi, 
I have a new issue. I have an aws linux server. I referred the below link
**http://elementalselenium.com/tips/38-headless**
which option is suitable for my server. 
share the clear steps for this issue.
Kindly do the needful

**Comment by legraphista** [comment]
There isn't a clear-cut suitable option, as it depends on how you setup your scripts and infrastructure

If you are running a process manager, like [PM2](http://pm2.keymetrics.io/), you'll probably want to start your xvfb and keep it running for all your apps.
```bash
pm2 start Xvfb -- :99 
export DISPLAY=:99 
pm2 start /path/to/my/app --update-env
```

But if you're running an one-time script, you could use
```bash
xvfb-run node /path/to/my/script
```

It's up to you how to setup your environment.

**Comment by pavithra-01** [comment]
**xvfb-run node /path/to/my/script**
This one working fine.

```
pm2 start Xvfb -- :99 
export DISPLAY=:99 
pm2 start /path/to/my/app --update-env
```
we need continuous running process 
It's not working. It creates two pm2 instance. 
kindly do a needful.
![2529](https://user-images.githubusercontent.com/54837070/64172401-8e452300-ce72-11e9-991f-afc494cf1e04.png)

**Comment by pavithra-01** [comment]
What is the meaning for --:99 in below statements 
pm2 start Xvfb -- :99 
What is the meaning for this statement
export DISPLAY=:99

**Comment by legraphista** [comment]
> What is the meaning for --:99 in below statements
> pm2 start Xvfb -- :99

in PM2, everything after ` -- ` is an argument that will be passed to the child process

`pm2 start Xvfb -- :99` will run `Xvfb :99` 
The `:99` argument tells Xvfb to create a virtual display on screen server 99

Run `man Xvfb` for more info

> export DISPLAY=:99

This tells the programs you'll be running next that they should use the screen server on port `:99` 

> pm2 start **/path/to/my/app** --update-env
> In this, bold statement - app path or script path ?

Path to your server.

Since i've noticed that your server startup script was already running, you may want to `pm2 restart index --update-env`

**Comment by pavithra-01** [comment]
Ok Thank you. It's working.
